Repository AY2021S1-CS2103-T16-3/tp, pull requests merged in 2020-11, with the labels that each got.

#170 Fix issue with restoring rooms from bin
  src/main/java/seedu/resireg/logic/commands/RestoreCommand.java
  src/main/java/seedu/resireg/storage/JsonAdaptedBinItem.java
  src/test/java/seedu/resireg/logic/commands/CommandTestUtil.java
  src/test/java/seedu/resireg/storage/JsonAdaptedBinItemTest.java
  src/test/java/seedu/resireg/testutil/TypicalBinItems.java
Labels: bugfix

#171 Purge Statistics
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/resireg/ui/MainPanel.java
  src/main/java/seedu/resireg/ui/PiechartPanel.java
  src/main/java/seedu/resireg/ui/PiechartsOnlyTab.java
  src/main/java/seedu/resireg/ui/PiechartsTab.java
  src/main/resources/view/Piechart.css
  src/main/resources/view/PiechartPanel.fxml
  src/main/resources/view/PiechartsOnlyTab.fxml
Labels: severity.VeryLow

#174 Bug Fix: Reallocate allows allocation of different students to the same room.
  docs/UserGuide.md
  src/main/java/seedu/resireg/logic/commands/AllocateCommand.java
  src/main/java/seedu/resireg/logic/commands/ReallocateCommand.java
  src/main/java/seedu/resireg/model/ResiReg.java
  src/main/java/seedu/resireg/model/allocation/Allocation.java
  src/main/java/seedu/resireg/model/allocation/UniqueAllocationList.java
Labels: bugfix

#176 Bug Fix: Fix room number error message and add-room UG details
  docs/UserGuide.md
  src/main/java/seedu/resireg/model/room/Floor.java
  src/main/java/seedu/resireg/model/room/RoomNumber.java
Labels: bugfix

#190 Make documentation more specific for archive and students commands
  docs/UserGuide.md
  docs/images/AfterArchive.png
  docs/images/BeforeArchive.png
  src/main/java/seedu/resireg/logic/commands/ListStudentsCommand.java
  src/main/java/seedu/resireg/model/util/SampleDataUtil.java
Labels: documentation-fix

#191 Add lysire ppp
  docs/UserGuide.md
  docs/team/lysire.md
Labels: priority.High

#197 Fix sequence diagram for delete-student and update PPP
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/team/jetnew.md
Labels: documentation-fix

#200 Update DG diagrams and fix formatting errors
  docs/DeveloperGuide.md
  docs/diagrams/SaveActivityDiagram.puml
  docs/diagrams/UndoRedoClassDiagram.puml
  docs/images/SaveActivityDiagram.png
  docs/images/UndoRedoClassDiagram.png
  docs/team/lysire.md
  src/main/java/seedu/resireg/commons/util/InvalidationListenerList.java
  src/main/java/seedu/resireg/logic/CommandHistory.java
  src/main/java/seedu/resireg/model/StatefulResiReg.java
  src/main/java/seedu/resireg/ui/ListPtr.java
Labels: documentation-fix

#201 Jingyen/final doc fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/resireg/logic/commands/ListRoomsCommand.java
Labels: documentation-fix

#206 Use case fixes
  docs/DeveloperGuide.md
Labels: documentation-fix

#205 Add final_v1 doc fixes
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/AllocationClassDiagram.puml
  docs/diagrams/ArchiveSemesterSequenceDiagram.puml
  docs/diagrams/BinClassDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/AllocationClassDiagram.png
  docs/images/ArchiveSemesterSequenceDiagram.png
  docs/images/BinClassDiagram.png
  docs/images/UndoSequenceDiagram.png
  docs/index.md
  docs/team/jingyenloh.md
Labels: documentation-fix
