Repository AY2021S1-CS2103-T16-3/tp, pull requests merged in 2020-10, with the labels that each got.

#84 Functionality Increment: Deallocate Command
  src/main/java/seedu/resireg/logic/commands/DeallocateCommand.java
  src/main/java/seedu/resireg/logic/parser/AddressBookParser.java
  src/main/java/seedu/resireg/logic/parser/DeallocateCommandParser.java
Labels: priority.High

#85 Functionality Increment: Reallocate Command
  src/main/java/seedu/resireg/logic/commands/ReallocateCommand.java
  src/main/java/seedu/resireg/logic/parser/AddressBookParser.java
  src/main/java/seedu/resireg/logic/parser/ReallocateCommandParser.java
Labels: priority.High

#87 Create PR template
  .github/pull_request_template.md
Labels: enhancement, priority.Medium

#88 Fix bug where room can be allocated to multiple students
  src/main/java/seedu/resireg/logic/commands/AllocateCommand.java
  src/main/java/seedu/resireg/logic/commands/ReallocateCommand.java
Labels: bugfix

#91 Fix user guide corrections
  docs/UserGuide.md
Labels: severity.VeryLow

#96 Refactoring with Allocation association class and Bug fix for delete/edit students' allocated rooms
  src/main/java/seedu/resireg/logic/CreateEditCopy.java
  src/main/java/seedu/resireg/logic/Logic.java
  src/main/java/seedu/resireg/logic/LogicManager.java
  src/main/java/seedu/resireg/logic/commands/AllocateCommand.java
  src/main/java/seedu/resireg/logic/commands/DeallocateCommand.java
  src/main/java/seedu/resireg/logic/commands/DeleteCommand.java
  src/main/java/seedu/resireg/logic/commands/EditCommand.java
  src/main/java/seedu/resireg/logic/commands/ListRoomCommand.java
  src/main/java/seedu/resireg/logic/commands/ReallocateCommand.java
  src/main/java/seedu/resireg/model/AddressBook.java
  src/main/java/seedu/resireg/model/Model.java
  src/main/java/seedu/resireg/model/ModelManager.java
  src/main/java/seedu/resireg/model/ReadOnlyAddressBook.java
  src/main/java/seedu/resireg/model/allocation/Allocation.java
  src/main/java/seedu/resireg/model/allocation/UniqueAllocationList.java
  src/main/java/seedu/resireg/model/allocation/exceptions/AllocationNotFoundException.java
  src/main/java/seedu/resireg/model/allocation/exceptions/DuplicateAllocationException.java
  src/main/java/seedu/resireg/model/room/Room.java
  src/main/java/seedu/resireg/model/student/Student.java
  src/main/java/seedu/resireg/model/util/SampleDataUtil.java
  src/main/java/seedu/resireg/storage/JsonAdaptedAllocation.java
  src/main/java/seedu/resireg/storage/JsonAdaptedRoom.java
  src/main/java/seedu/resireg/storage/JsonAdaptedRoomStudent.java
  src/main/java/seedu/resireg/storage/JsonAdaptedStudent.java
  src/main/java/seedu/resireg/storage/JsonAdaptedStudentRoom.java
  src/main/java/seedu/resireg/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/resireg/ui/MainWindow.java
  src/main/java/seedu/resireg/ui/RoomCard.java
  src/main/java/seedu/resireg/ui/RoomListPanel.java
  src/main/java/seedu/resireg/ui/StudentCard.java
  src/main/java/seedu/resireg/ui/StudentListPanel.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidStudentAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/resireg/logic/commands/AddCommandTest.java
  src/test/java/seedu/resireg/logic/commands/ListRoomCommandTest.java
  src/test/java/seedu/resireg/model/AddressBookTest.java
  src/test/java/seedu/resireg/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/resireg/testutil/StudentBuilder.java
Labels: bugfix, priority.High, severity.High

#106 Add unit tests for allocate, deallocate, reallocate commands and JsonAdaptedRoom
  src/main/java/seedu/resireg/storage/JsonAdaptedRoom.java
  src/test/java/seedu/resireg/logic/commands/AllocateCommandTest.java
  src/test/java/seedu/resireg/logic/commands/DeallocateCommandTest.java
  src/test/java/seedu/resireg/logic/commands/ReallocateCommandTest.java
  src/test/java/seedu/resireg/storage/JsonAdaptedRoomTest.java
  src/test/java/seedu/resireg/testutil/AllocationBuilder.java
  src/test/java/seedu/resireg/testutil/TypicalAllocations.java
  src/test/java/seedu/resireg/testutil/TypicalIndexes.java
Labels: type.Chore

#119 Refactor undo/redo functionality and tests, fix UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SaveActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/SaveActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  src/main/java/seedu/resireg/model/ModelManager.java
  src/main/java/seedu/resireg/model/StatefulResiReg.java
  src/main/java/seedu/resireg/model/VersionedResiReg.java
  src/test/java/seedu/resireg/model/StatefulResiRegTest.java
  src/test/java/seedu/resireg/model/VersionedResiRegTest.java
Labels: priority.Medium, type.Chore
